# Generated by Django 5.1.1 on 2025-05-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ending',
            fields=[
                ('ending_id', models.AutoField(primary_key=True, serialize=False)),
                ('ending_description', models.TextField(blank=True, null=True)),
                ('ending_picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('api_title', models.CharField(blank=True, max_length=255, null=True)),
                ('min_salary', models.IntegerField()),
                ('max_salary', models.IntegerField()),
                ('pension', models.CharField(max_length=255)),
                ('job_outfit', models.ImageField(blank=True, default='sprite_base.png', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('full_time_education', models.BooleanField(blank=True, null=True)),
                ('final_money', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
